services:
  minirt:
    container_name: minirt
    build:
      context: .
    volumes:
      - .:/home/program
    working_dir: /home/program
    environment:
      - DISPLAY=host.docker.internal:0
    command: /bin/bash
    tty: true
